# Homework Section 5

### 1. What does Pandas stand for?

It stands for or was derived from Panel Data and Python Data Analysis

### 2. What are the 2 collections used in Pandas?

The two collections used in Pandas are series and data frames.

### 3. Name 4 things Pandas can do for us.

Pandas can manipulate data, prepare data, model data, and analyze the data.

### 4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?

inplace = True

### 5. What is a CSV?

A CSV is a comma separated values file.

### 6. When cleaning data what values do we not like in our data?

NA or NaN values

In [ ]:
####Please Complete this Coding Exercise:####

#7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- .reshape()

import numpy as np

#shape - 3 dimensions, first dimension has two elements - number of rows, second dimention has three elements - number of columns, and the third dimension has two elements
#ok it seems for this 2,3,2 array to calculate needed elements 2 multiplied by 3 then multipled by 2 will give me the needed number of elements

arrayA = np.array([1,2,3,4,5,6,7,8,9,10, 11, 12])

newA = arrayA.reshape(2,3,2)

print(newA)
print(newA.shape)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


In [6]:
#8. Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20

arrayLinear = np.linspace(0, 20, num = 6, endpoint = True)

print(arrayLinear)

#9. Make a Deep Copy of the above array

import copy

arrayTwin = copy.deepcopy(arrayLinear)

print(arrayTwin)


[ 0.  4.  8. 12. 16. 20.]
[ 0.  4.  8. 12. 16. 20.]


In [7]:
#10. Concatenate these 3 arrays into a new array named 'newArray'...

arrayA = ([[25, 16]])
arrayB = ([[11, 2], [13, 4]])
arrayC = ([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((arrayA, arrayB, arrayC), axis = 0)

print(newArray)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [9]:
#11. Sort 'newArray' in order into 'sortedArray'

sortedArray = np.sort(newArray)

print(sortedArray)

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [ ]:
#12. Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.
#confused is this the array from sortedArray or the first array from question 7????


#tuple_a, tuple_b, tuple_c = newArray

#print("a = ", tuple_a)
#print("b = ", tuple_b)
#print("c = ", c)
#print("d = ", d)

# i get the error too many values to unpack, please advice
##HELP!!!!!

In [43]:

#13. Combined and sort the following arrays into one called 'comboArray' ...

one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate((one, two, three), axis = 0)

updatedArray = np.sort(comboArray)

print(updatedArray)

#14. Take 'comboArray' and perform the following slicing activities:

#print sec1 - the 2nd element

print(updatedArray[1])

#print sec2 - all elements from the 3rd element to the last

print(updatedArray[2:])

#print sec3 - all elements from the 4th to the 14th elements

print(updatedArray[4:15])

#print sec4 - the last 6 elements

print(updatedArray[-7:-1])

#print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.

print(updatedArray[-26:-10])

#print sec6 - from #20 every even element to the end
#unsure how this one worked, i have questions

print(updatedArray[16::2])

#print sec7 - from the last element moving forward, every 5th element.

print(updatedArray[:-1:5])


[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
1
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 4  5  6  7 10 11 12 13 14 15 16]
[21 22 23 24 25 26]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
[20 22 24 26]
[ 0  5 12 17 24]


In [46]:
#15. Using Series, create a DataFrame that looks like this:

#IngredientsQuantityUnitFlour4cupsMilk1cupEggs2largeSpam1can

#Name: Dinner, dtype: object
import pandas as pd

Ingredients = pd.Series(["Flour", "Milk", "Eggs", "Spam"], dtype = object, name = "Ingredients")
Quantity = pd.Series([4, 1, 2, 1], dtype = object, name = "Quantity")
Units = pd.Series(["cups", "cup", "large", "can"], dtype=object, name = "Unit")

print(Ingredients)
print(Quantity)
print(Units)

Dinner = pd.concat([Ingredients, Quantity, Units], axis = 1)
print(Dinner)



0    Flour
1     Milk
2     Eggs
3     Spam
Name: Ingredients, dtype: object
0    4
1    1
2    2
3    1
Name: Quantity, dtype: object
0     cups
1      cup
2    large
3      can
Name: Unit, dtype: object
  Ingredients Quantity   Unit
0       Flour        4   cups
1        Milk        1    cup
2        Eggs        2  large
3        Spam        1    can


In [ ]:
#16. Take this data and create a DataFrame named studentData

dataDict = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
    'Age': [21, 23, 24, 21],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']}

studentData = pd.DataFrame(dataDict)
print(studentData)

#17. Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

studentData.insert(4, "desserts", ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"], True)
print(studentData)

#18. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

studentData.sort_values(by = ["Name", "address"], inplace = True, ascending = True)
print(studentData)


      Name  Height Qualification  address      desserts  Age        Pets  \
0      Jai     5.1           Msc    Delhi     ice cream   21         Dog   
1  janusha     6.2            MA     Doha  Cashew Fudge   23       Bunny   
2   Gaurav     5.1           Msc  Chennai       waffels   24  Chinchilla   
3     Anuj     5.2           Msc   Dakhar  Carrot Halwa   21      Parrot   

            sport  
0           Darts  
1      Basketball  
2  PaddleBoarding  
3         Cricket  
      Name  Height Qualification  address      desserts  Age        Pets  \
3     Anuj     5.2           Msc   Dakhar  Carrot Halwa   21      Parrot   
2   Gaurav     5.1           Msc  Chennai       waffels   24  Chinchilla   
0      Jai     5.1           Msc    Delhi     ice cream   21         Dog   
1  janusha     6.2            MA     Doha  Cashew Fudge   23       Bunny   

            sport  
3         Cricket  
2  PaddleBoarding  
0           Darts  
1      Basketball  


In [69]:
#19. Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

df.to_csv("cows_and_goats.csv", index = False)

In [77]:
#20. Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

df = pd.DataFrame({"Vegetable" : ["celery", "broccoli", "spinach"]})
                                  
df.to_csv("vegetables.csv", index = False)          

df.insert(1, "quantity", [1, 2, 5], True)

print(df)

df.to_csv("vegetable_harvest.csv", index= False)



  Vegetable  quantity
0    celery         1
1  broccoli         2
2   spinach         5
